
app = 'automod'
primary_region = 'lax'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  max_machines_running = 1
  min_machines_running = 1
  [http_service.concurrency]
      type = "requests"
      soft_limit = 100
      hard_limit = 200
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  size = "shared-cpu-4x"
  memory = "2gb"
